region                 = "ap-south-1"
platform               = "platform"
environment            = "stage"
instance_type          = "t3.micro"
ami_ssm_parameter_name = "/sc/ec2-go-service/stage/ami-id"
